name: 'Build Custom Alpine Image'
description: 'Builds a custom Alpine Linux Docker image with specified packages'
inputs:
  packages:
    description: 'Packages to include'
    required: true
  cache-key:
    description: 'Cache key for Docker image'
    required: true
runs:
  using: "composite"
  steps:
      - name: Download Image Name Artifact
        uses: actions/download-artifact@v2
        with:
          name: image-name
          path: .
        
      - name: Read Image Name
        id: read-imagename
        run: |
          echo "::set-output name=imagename::$(cat image_name.txt)"
        shell: bash

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/docker-cache
          key: ${{ inputs.cache-key }}
          restore-keys: ${{ inputs.cache-key }}

      - name: Install wget
        run: |
          if command -v apt-get >/dev/null; then
            sudo apt-get update
            sudo apt-get install -y wget
          elif command -v yum >/dev/null; then
            sudo yum update -y
            sudo yum install -y wget
          else
            echo "Package manager not found. Unable to install wget."
            exit 1
          fi
        shell: bash

      - name: Build and import custom Alpine base image
        run: |
          mkdir -p /tmp/docker-cache
          wget https://raw.githubusercontent.com/alpinelinux/alpine-make-rootfs/v0.7.0/alpine-make-rootfs
          chmod +x alpine-make-rootfs
          sudo ./alpine-make-rootfs --branch v3.19 --packages '${{ inputs.packages }} ca-certificates' ./base-alpine-rootfs.tar.gz
          sudo docker import -c 'cmd ["sh"]' ./base-alpine-rootfs.tar.gz ${{ steps.read-imagename.outputs.imagename }}
          sudo docker save ${{ steps.read-imagename.outputs.imagename }} > /tmp/docker-cache/my-custom-alpine.tar
          echo ${{ steps.read-imagename.outputs.imagename }} > /tmp/docker-cache/image-tag.txt
        shell: bash

      - name: Upload Docker image to cache
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-my-custom-alpine
          path: |
            /tmp/docker-cache/my-custom-alpine.tar
            /tmp/docker-cache/image-tag.txt
